### ISSUE TITLE
v0.13.0+ - Cannot read properties of undefined (reading 'parent')

### ISSUE THREAD

**Issue by Plechoo** [mmisty/cypress-allure-adapter#87] opened 2023-11-21 10:27 UTC
version 0.13.0+ i have this problem

```
The following error originated from your test code, not from Cypress.

  > Cannot read properties of undefined (reading 'parent')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

now i use v0.12.1 and all its OK, i try 0.12.x and its fine too.

**Comment by mmisty** [comment] 2023-11-21 10:29
@Plechoo hello
Could you please attach stack trace

**Comment by Plechoo** [comment] 2023-11-21 10:31
@mmisty hi ofc

`  We dynamically generated a new test to display this failure.
      at describeWithTags (webpack://cypress-tests-for-myport/./node_modules/@mmisty/cypress-tags/setup/index.js:94:0)
      at eval (webpack://cypress-tests-for-myport/./cypress/e2e/Client/backoffice/smoke/existingClient/client_FO_existingClientInApp.cy.ts:4:0)
      at eval (https://backoffice-stage.finportal.sk/__cypress/tests?p=cypress/e2e/Client/backoffice/smoke/existingClient/client_FO_existingClientInApp.cy.ts:317:3)
      at eval (https://backoffice-stage.finportal.sk/__cypress/tests?p=cypress/e2e/Client/backoffice/smoke/existingClient/client_FO_existingClientInApp.cy.ts:319:12)
      at eval (<anonymous>)
`

**Comment by mmisty** [comment] 2023-11-21 10:34
@Plechoo Thank you!
could you please also attach when you have time 
1 test file if that's possible with which it reproduces
2 support/e2e file
3 cypress configuration 
4 plugins configuration 

thank you

**Comment by mmisty** [comment] 2024-05-30 21:40
closing since no updates. please try latest version 0.16.5

**Closed** 2024-05-30 21:40 UTC
Labels: waiting info
