### ISSUE TITLE
Missing long assertion messages for steps (assert)

### ISSUE THREAD

**Issue by MDzyga** [mmisty/cypress-allure-adapter#34] opened 2023-09-30 08:54 UTC
Hello @mmisty :)
We noticed that sometimes assert is empty in Allure. Do you know why it can happen?
I'm not sure where is an issue. We're using the latest verion of allure plugin for jenkins and cypress in version 13.0.0.
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/3e05d6b8-6b70-4162-b9ee-e06fdcf01e64)

1st issue - marked expect with custom message is missing
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/28a9d4c2-cc43-48cf-8d1a-a5211960bfda)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/99c95100-eb01-47e4-b352-7c760dc8773f)

The 2nd issue - it's more strange - in this case all marked asserts disappeared
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/1eb9cf22-7c6b-4775-8992-d0951abbfd97)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/219f1ff1-7905-4d18-8816-006fb866930d)

**Comment by mmisty** [comment] 2023-10-01 08:46
Hi @MDzyga,

Thank you for reporting that. I noticed that in reports earlier, but I could not reproduce.

Could you please provide whole test that reproduces the problem, also screenshot of cypress command log with that assertions (or even better video of running test).

Thank you

**Comment by MDzyga** [comment] 2023-10-01 11:03
AdaptersService:
```
export class AdaptersService {
  readonly URL: string = `${Global.API_URL}${Endpoints.ADAPTERS}`;

  getAll(): Cypress.Chainable<Cypress.Response<IAdapter[]>> {
    return cy.request<IAdapter[]>({
      method: Methods.GET,
      url: this.URL,
    });
  };
}
```

1st issue:
```
it('Get All Adapters', () => {
        const assertions: IAdapter[] = [
          {
            name: "CSV",
            modes: [LimsMode.Download],
          },
          {
            name: "HL7 2.5.1",
            modes: [LimsMode.Broadcast, LimsMode.Query],
          },
          {
            name: "XML",
            modes: [LimsMode.Download],
          },
        ];

        service
          .getAll()
          .then((response: Cypress.Response<IAdapter[]>) => {
            expect(response.status, "Response status").to.equal(200);

            assertions.forEach((expectedAdapter: IAdapter) => {
              const adapter: IAdapter = response.body.find((item: IAdapter) => item.name === expectedAdapter.name);

              expect(adapter, `Adapter with name: ${expectedAdapter.name} exist`).to.exist;

              expectedAdapter.modes.forEach((expectedMode: string) => {
                const mode: string = adapter.modes.find((item: string) => item === expectedMode);
                expect(mode, `Mode: ${mode} found in adapter: ${expectedAdapter.name}`).to.exist;
              });
            });
          });
      });
```

2nd issue:
```
it('Adapters versioning', () => {
        const assertionsDuplicated: IAdapter[] = [
          {
            name: "Qiagen.CI.LIMSconnector.Adapters.CSV.v1",
            message: "Duplicated",
            modes: [],
          },
          {
            name: "Qiagen.CI.LIMSconnector.Adapters.HL7_2_5_1.v1",
            message: "Duplicated",
            modes: [],
          },
          {
            name: "Qiagen.CI.LIMSconnector.Adapters.XML.v1",
            message: "Duplicated",
            modes: [],
          },
        ];

        const assertionsIncompatible: IAdapter[] = [
          {
            name: "Qiagen.CI.LIMSconnector.Adapters.CSV.v0",
            message: "Incompatible with current version",
            modes: [],
          }, {
            name: "Qiagen.CI.LIMSconnector.Adapters.HL7_2.5.1.v0",
            message: "Incompatible with current version",
            modes: [],
          }, {
            name: "Qiagen.CI.LIMSconnector.Adapters.XML.v0",
            message: "Incompatible with current version",
            modes: [],
          },
        ];

        service
          .getAll()
          .then((response: Cypress.Response<IAdapter[]>) => {
            expect(response.status, "Response status").to.equal(200);
            expect(response.body.length, "Number of available adapters").to.equal(9);

            assertionsIncompatible.forEach((expectedAdapter: IAdapter) => {
              const adapter: IAdapter = response.body.find((item: IAdapter) => item.name === expectedAdapter.name);

              expect(adapter, `Adapter with name ${expectedAdapter.name} exist`).to.exist;
              expect(adapter.message, `Message error for adapter with name ${expectedAdapter.name}`).to.equal(expectedAdapter.message);
            });

            assertionsDuplicated.forEach((expectedAdapter: IAdapter) => {
              const adapter: IAdapter = response.body.find((item: IAdapter) => item.name === expectedAdapter.name);

              expect(adapter, `Adapter with name ${expectedAdapter.name} exist`).to.exist;
              expect(adapter.message, `Message error for adapter with name ${expectedAdapter.name}`).to.equal(expectedAdapter.message);
            });
          });
      });
    });
```

[allure-results.zip](https://github.com/mmisty/cypress-allure-adapter/files/12776991/allure-results.zip)
https://github.com/mmisty/cypress-allure-adapter/assets/38663990/77a6102d-88d8-4e6b-a8a6-89e0f3023562

Let me know if you need something more

**Comment by MDzyga** [comment] 2023-10-01 11:12
Screenshots
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/d58b8da2-ae36-4d26-893f-834dd6e0eb4d)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/68ca2325-d045-4122-874d-e10354f014e8)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/bbbf3144-1ca6-4f6d-8486-356fd23379e1)

**Comment by mmisty** [comment] 2023-10-01 13:14
@MDzyga, thank you for provided artifacts.
I still could not reproduce, but  I tried to fix that in version 0.10.6. Could you please check and confirm whether the issue still exist or not. 
Thank you

**Comment by mmisty** [comment] 2023-10-01 13:31
@MDzyga sorry, I found steps, 0.10.6 doesn't fix that. I will try to do fix tomorrow

**Comment by mmisty** [comment] 2023-10-01 21:39
@MDzyga issue was fixed in 0.10.7 version. Could you please try. Thanks.

**Closed** 2023-10-01 21:44 UTC
Labels: bug, medium

**Comment by MDzyga** [comment] 2023-10-02 05:32
Confirm :) Thank you :)

**Comment by jprealini** [comment] 2023-11-16 18:18
@MDzyga wonder if you could share the basic configuration for allowing the adapter to generate results and the report in Jenkins... I just posted an [issue](https://github.com/mmisty/cypress-allure-adapter/issues/85) where I am running the jenkins job, but there are no results generated in the allure-results folder... 
Thanks
