### ISSUE TITLE
v0.15.2 cannot run tests in Firefox "The operation is insecure" in websocket.js 16:1

### ISSUE THREAD

**Issue by thomasKuntermannDiva-e** [mmisty/cypress-allure-adapter#81] opened 2023-11-14 09:05 UTC
With my local setup in package.json, we cannot run tests with Cypress Runner locally or from commandline with FIREFOX anymore.
Directly after clicking a .feature test from e.g. the Cypress runner, this error is thrown:
<img width="947" alt="Bildschirmfoto 2023-11-14 um 10 02 51" src="https://github.com/mmisty/cypress-allure-adapter/assets/27360136/1c66f674-6b4b-4656-aae8-23ffd14b1d5f">

here is my dependency list from package.json:

> "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "19.1.0",
    "@cucumber/cucumber": "10.0.1",
    "@cypress/browserify-preprocessor": "^3.0.2",
    "@mmisty/cypress-allure-adapter": "0.15.2",
    "@typescript-eslint/eslint-plugin": "^5.9.0",
    "@typescript-eslint/parser": "^5.9.0",
    "allure-commandline": "2.16.1",
    "cypress": "13.4.0",
    "cypress-visual-regression": "^1.1.0",
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-chai-friendly": "^0.6.0",
    "eslint-plugin-cucumber": "^2.0.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.2.0",
    "jsdoc": "^4.0.2",
    "mochawesome": "^7.0.1",
    "playwright-webkit": "^1.26.0",
    "resolve": "^1.20.0",
    "tsify": "^5.0.4",
    "typedoc": "^0.22.9",
    "typescript": "^4.5.2"
  },

With Chrome, the test execution seems to work still fine.
Would be nice to get this error resolved.

Best regards

Thomas

**Comment by mmisty** [comment] 2023-11-14 09:23
@thomasKuntermannDiva-e  hi
Could you please let me know:
 - with what version this was executed fine? 
 - what firefox version fails? 
- you cypress.config.ts

I could not reproduce that yet

**Comment by thomasKuntermannDiva-e** [comment] 2023-11-14 09:43
@mmisty this is our cypress-config.ts

> import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor'
// @ts-ignore
import browserify from '@badeball/cypress-cucumber-preprocessor/browserify'
const { configureAllureAdapterPlugins } = require('@mmisty/cypress-allure-adapter/plugins')

const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin')

export const defaultGlobalConfigValues = {
  video: false,
  screenshotOnRunFailure: true,
  screenshotsFolder: './cypress/screenshots/actual',
  trashAssetsBeforeRuns: true,
  viewportWidth: 1440,
  viewportHeight: 1000,
  requestTimeout: 30000,
  defaultCommandTimeout: 10000,
  responseTimeout: 30000,
  userAgent: 'cypress/test-automation',
  watchForFileChanges: false,
  chromeWebSecurity: false,
  experimentalWebKitSupport: true,
  blockHosts: [],
  includeShadowDom: true,
  modifyObstructiveCode: false,
  scrollBehavior: 'center',
  videoCompression: 16,
  e2e: {
    specPattern: '**/*.feature',
    testIsolation: true,
    excludeSpecPattern: '**/ignoreme/*',
    async setupNodeEvents (
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
      await addCucumberPreprocessorPlugin(on, config)

      on(
        'file:preprocessor',
        browserify(config, {
          typescript: require.resolve('typescript')
        })
      )

      getCompareSnapshotsPlugin(on, config)
      configureAllureAdapterPlugins(on, config)
      return config
    }
  },
  env: {
    allure: true,
    tmsPrefix: 'https://JIRA-DOMAIN/',
    issuePrefix: 'https://JIRA-DOMAIN/',
    failSilently: false,
    enableScreenshotDiffPlugin: true,
    'X-Target-Device': '',
    slowCommandTimeout: 20000,
    graphQlToken: '',
    shopCustomerEmail: '',
    shopCustomerPassword: '',
    shopCustomerCartId: ''
  }
}

(x) not working Firefox version = 119.0.1
(/) working Chrome version = 119.0.6045.123
(/) working Edge version = 119.0.2151.58

Thanks for the quick response!

**Comment by mmisty** [comment] 2023-11-14 09:56
@thomasKuntermannDiva-e  - did this ever executed fine on Firefox?

**Comment by thomasKuntermannDiva-e** [comment] 2023-11-14 10:00
yes. until we tried to update from Cypress 12.12.0 to a higher version, what needed us to switch to your allure report package. I'll try with some older versions... keep you posted

**Comment by thomasKuntermannDiva-e** [comment] 2023-11-14 10:08
I retried with Cypress 13.4.0 & last shelex/cypress-allure-plugin -> Firefox works properly.
Here's the test package.json "devDependencies" list:

>  "@badeball/cypress-cucumber-preprocessor": "19.1.0",
    "@cucumber/cucumber": "^7.3.1",
    "@cypress/browserify-preprocessor": "^3.0.2",
    "@shelex/cypress-allure-plugin": "2.40.0",
    "@typescript-eslint/eslint-plugin": "^5.9.0",
    "@typescript-eslint/parser": "^5.9.0",
    "allure-commandline": "^2.13.8",
    "cypress": "13.4.0",
    "cypress-visual-regression": "^1.1.0",
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-chai-friendly": "^0.6.0",
    "eslint-plugin-cucumber": "^2.0.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.2.0",
    "jsdoc": "^4.0.2",
    "mochawesome": "^7.0.1",
    "playwright-webkit": "^1.26.0",
    "resolve": "^1.20.0",
    "tsify": "^5.0.4",
    "typedoc": "^0.22.9",
    "typescript": "^4.5.2"

**Comment by mmisty** [comment] 2023-11-14 10:10
Trying to understand - Is that right that Firefox has never worked for you with `@mmisty/cypress-allure-adapter`?

**Comment by mmisty** [comment] 2023-11-14 10:15
@thomasKuntermannDiva-e  so I could not replicate that.
Could you please create reproducible repo - you can use these examples to start with https://github.com/mmisty/cypress-allure-adapter-example

**Comment by thomasKuntermannDiva-e** [comment] 2023-11-14 10:16
I tried with your version 0.13.0 & 0.14.0 as well -> Firefox does not work.

I'll try to create an example with your test project

**Comment by thomasKuntermannDiva-e** [comment] 2023-11-14 11:22
I could solve the issue for Firefox by adding this to cypress.config.ts:

```
 on('before:browser:launch', (browser, launchOptions) => {
             if (browser.family === 'firefox') {
          // launchOptions.preferences is a map of preference names to values
          launchOptions.preferences['network.websocket.allowInsecureFromHTTPS'] = true
          return launchOptions
        }
})
```

following this guide -> https://docs.cypress.io/api/plugins/browser-launch-api#Changing-browser-preferences

I was not able to reproduce with your example project https://github.com/mmisty/cypress-allure-adapter-example. Must be something in our customised setup. I will go on finding the root-cause and get back here. 

(other projects from my company with very different Cypress setups, are also having this issue and using my workaround.)

Thanks so far!

**Comment by mmisty** [comment] 2024-08-14 10:11
Closing since no updates received

**Closed by mmisty** 2024-08-14 10:11 UTC
Labels: waiting info
