### ISSUE TITLE
Allure report doesn't show all executed cases in the report

### ISSUE THREAD

**Issue by AhmadfBaker** [mmisty/cypress-allure-adapter#103] opened 2024-03-03 19:04 UTC
Hi @mmisty,

I see that sometime the allure report doesn't contains some of the passed cases. and after debugging i found these cases exist in the code, and already executed in CI (Checked from jenkins logs). And after the automation finished. mochawesome and allure reports generated. 
- mochawesome report contains all cases (passed and failed)
- allure report not contains all cases from passed ones. 
Did you faced this issue before? 

Please note that the number of test cases is larg (~2700 test case)
mochawesome always show the correct number of total test cases, but allure shown less than 2700 in sometimes.

**Comment by mmisty** [comment] 2024-03-06 10:28
Hello @AhmadfBaker 
Please make sure you tests have uniq names because histodyId is being generated basing on full name of the test (all nested suites + test name) 
So if you have several files containing same chain of suite / test name they will be considered as one test and duplicates will be shown as retries for that test.

You can [specify your own history id](https://github.com/mmisty/cypress-allure-adapter/blob/main/docs/interface.md#historyid) or your own full name:

```javascript
// put it into setup file
Cypress.Allure.on('test:started', test => {
    Cypress.Allure.fullName(`${Cypress.spec.name} ${test.fullTitle()}`);
  });
```

If this is not the case it would be helpful to have reproducible example, or at least `allure-results` with which you've built report with missing results

**Comment by AhmadfBaker** [comment] 2024-03-06 10:47
Hi @mmisty 
Thanks for your reply, 
Actually, What we missed here is that sometimes the report show all cases and sometimes the report missed some cases, and after debugging, i found that the missing cases from the report already executed in CI. only not shown in the report. 
And for the duplicate names, all tests have unique names ( because i have test case id for each test)
and when checking the mochaswome report before generating the allure, all cases exist there. but in the allure not all cases there. 
Do you know if Mochawsome files could have same name before generating the allure? or it's impossible? 

Thanks.

**Comment by mmisty** [comment] 2024-03-06 10:52
@AhmadfBaker I'm not aware of mocha awsome.
Ok, then to reproduce the issue could you please provide allure-results or reproducible example
Other thing - to isolate the problem you can count how many files with `*-result.json` extension within allure results folder - It should be equal to tests count (2700)

**Comment by mmisty** [comment] 2024-08-14 10:11
Closing since no updates received

**Closed by mmisty** 2024-08-14 10:11 UTC
Labels: waiting info
